Some stuff
fajfer/billy-h-scraper pull request #1
Opened 2022-09-12 19:52 UTC by Electronic-Mango

2022-09-12 20:06 UTC, fajfer requested changes
wrzucilbym poetry w międzyczasie i poprawił main.py tak jak jest to zrobione w poprzednim bocie

btw, wrzuciło ci się history, bo nie używasz `git add -u` tylko `git add .`

2022-09-12 20:06 UTC, fajfer commented on Dockerfile
> +COPY requirements.txt .
poetry albo śmierć

2022-09-13 17:31 UTC, Electronic-Mango commented on Dockerfile
> +COPY requirements.txt .
Wybieram śmierć.

2022-09-13 17:34 UTC, Electronic-Mango commented
@fajfer history było wrzucone specjalnie, inaczej Compose podłącza "history" jako katalog i później się wywala, bo nie może do niego nic zapisać.
Poetry wydaje mi się overkillem na ten projekt, więc na razie jest po staremu.
Nie wydaje mi się, żeby dalsze modyfikacje main.py były przedmiotem tego PR.

2022-09-13 18:16 UTC, fajfer approved these changes

2022-09-13 18:17 UTC, merged